package jobtracker

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/TheBharathProject/sypher-api/internal/ai"
	"github.com/TheBharathProject/sypher-api/internal/auth"
	"github.com/TheBharathProject/sypher-api/internal/httpx"
)

// unsafeFilenameChars matches any character that is not alphanumeric,
// a hyphen, underscore, or dot. Used to sanitize Content-Disposition filenames.
var unsafeFilenameChars = regexp.MustCompile(`[^a-zA-Z0-9._\-]`)

// sanitizeFilename strips unsafe characters from a filename, replaces them
// with hyphens, collapses consecutive hyphens, trims leading/trailing hyphens,
// and truncates at 200 characters.
func sanitizeFilename(name string) string {
	name = strings.TrimSpace(name)
	name = unsafeFilenameChars.ReplaceAllString(name, "-")
	// Collapse consecutive hyphens.
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}
	name = strings.Trim(name, "-")
	if len(name) > 200 {
		name = name[:200]
	}
	if name == "" {
		name = "download.pdf"
	}
	return name
}

// ----------------------------------------------------------------------------
// PDF builder helpers — each returns a ready-to-output *fpdf.Fpdf.
// Headers MUST be set on the http.ResponseWriter before calling pdf.Output(w).
// ----------------------------------------------------------------------------

// buildCoverLetterPDF creates a formatted cover letter PDF from text parts.
// Uses Helvetica (built-in, no font file required) with UnicodeTranslator for
// common Latin-extended characters. Returns the Fpdf object; caller streams it.
func buildCoverLetterPDF(text, company, role string) (*fpdf.Fpdf, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(25, 25, 25)
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pageW, _ := pdf.GetPageSize()
	bodyW := pageW - 50 // left(25) + right(25)

	// Header: Company (bold 14pt)
	pdf.SetFont("Helvetica", "B", 14)
	lineH := pdf.PointConvert(14)
	if company != "" {
		pdf.MultiCell(bodyW, lineH, tr(company), "", "L", false)
		pdf.Ln(2)
	}

	// Subtitle: Role (regular 12pt)
	pdf.SetFont("Helvetica", "", 12)
	lineH12 := pdf.PointConvert(12)
	if role != "" {
		pdf.MultiCell(bodyW, lineH12, tr(role), "", "L", false)
		pdf.Ln(2)
	}

	// Date line
	pdf.SetFont("Helvetica", "", 10)
	lineH10 := pdf.PointConvert(10)
	pdf.MultiCell(bodyW, lineH10, time.Now().Format("2 January 2006"), "", "L", false)
	pdf.Ln(6)

	// Body: cover letter text (11pt)
	pdf.SetFont("Helvetica", "", 11)
	lineH11 := pdf.PointConvert(11) * 1.4
	pdf.MultiCell(bodyW, lineH11, tr(text), "", "L", false)

	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.MultiCell(bodyW, pdf.PointConvert(8), "Generated by Pegasus · sypher.in/pegasus", "", "C", false)

	if err := pdf.Error(); err != nil {
		return nil, fmt.Errorf("build cover letter pdf: %w", err)
	}
	return pdf, nil
}

// buildTweakPDF creates a formatted resume tweak PDF.
func buildTweakPDF(title, bodyText string) (*fpdf.Fpdf, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pageW, _ := pdf.GetPageSize()
	bodyW := pageW - 40 // left(20) + right(20)

	// Title (bold 14pt)
	pdf.SetFont("Helvetica", "B", 14)
	lineH14 := pdf.PointConvert(14)
	pdf.MultiCell(bodyW, lineH14, tr(title), "", "L", false)
	pdf.Ln(2)

	// Created date (regular 10pt)
	pdf.SetFont("Helvetica", "", 10)
	lineH10 := pdf.PointConvert(10)
	pdf.MultiCell(bodyW, lineH10, time.Now().Format("2 January 2006"), "", "L", false)
	pdf.Ln(6)

	// Body: tweaked resume text (10pt, line spacing 1.3)
	pdf.SetFont("Helvetica", "", 10)
	lineH := pdf.PointConvert(10) * 1.3
	pdf.MultiCell(bodyW, lineH, tr(bodyText), "", "L", false)

	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.MultiCell(bodyW, pdf.PointConvert(8), "Generated by Pegasus · sypher.in/pegasus", "", "C", false)

	if err := pdf.Error(); err != nil {
		return nil, fmt.Errorf("build tweak pdf: %w", err)
	}
	return pdf, nil
}

// buildReportPDF creates a formatted resume analysis report PDF.
// plainText should already have markdown syntax stripped by the caller.
func buildReportPDF(plainText string, score int, date string) (*fpdf.Fpdf, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(25, 25, 25)
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	tr := pdf.UnicodeTranslatorFromDescriptor("")
	pageW, _ := pdf.GetPageSize()
	bodyW := pageW - 50 // left(25) + right(25)

	// Title (bold 16pt)
	pdf.SetFont("Helvetica", "B", 16)
	lineH16 := pdf.PointConvert(16)
	pdf.MultiCell(bodyW, lineH16, "Resume Analysis Report", "", "L", false)
	pdf.Ln(2)

	// Date subtitle (regular 12pt)
	pdf.SetFont("Helvetica", "", 12)
	lineH12 := pdf.PointConvert(12)
	pdf.MultiCell(bodyW, lineH12, date, "", "L", false)
	pdf.Ln(4)

	// Score line (bold 12pt) — only rendered when score > 0
	if score > 0 {
		pdf.SetFont("Helvetica", "B", 12)
		pdf.MultiCell(bodyW, lineH12, fmt.Sprintf("Score: %d/100", score), "", "L", false)
		pdf.Ln(4)
	}

	// Body (11pt)
	pdf.SetFont("Helvetica", "", 11)
	lineH11 := pdf.PointConvert(11)
	pdf.MultiCell(bodyW, lineH11, tr(plainText), "", "L", false)

	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.MultiCell(bodyW, pdf.PointConvert(8), "Generated by Pegasus · sypher.in/pegasus", "", "C", false)

	if err := pdf.Error(); err != nil {
		return nil, fmt.Errorf("build report pdf: %w", err)
	}
	return pdf, nil
}

// stripMarkdown performs a best-effort strip of common markdown syntax so the
// text reads cleanly in a PDF. It handles headings, bold/italic, code fences,
// and horizontal rules.
var (
	mdHeading   = regexp.MustCompile(`(?m)^#{1,6}\s+`)
	mdBoldItal  = regexp.MustCompile(`\*{1,3}([^*]+)\*{1,3}`)
	mdCodeFence = regexp.MustCompile("(?m)^```[^\\n]*\\n?")
	mdInlineCode = regexp.MustCompile("`([^`]+)`")
	mdHRule     = regexp.MustCompile(`(?m)^[-*_]{3,}\s*$`)
)

func stripMarkdown(md string) string {
	s := mdHeading.ReplaceAllString(md, "")
	s = mdBoldItal.ReplaceAllString(s, "$1")
	s = mdCodeFence.ReplaceAllString(s, "")
	s = mdInlineCode.ReplaceAllString(s, "$1")
	s = mdHRule.ReplaceAllString(s, "")
	return strings.TrimSpace(s)
}

// streamPDF sets Content-Type / Content-Disposition headers and writes the PDF
// bytes to w. Headers must be set before Output writes the first byte.
// If Output errors after headers are committed, we log via the package-level
// slog default logger (the only logger available at this scope).
func streamPDF(w http.ResponseWriter, pdf *fpdf.Fpdf, filename string) {
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	if err := pdf.Output(w); err != nil {
		// Headers are already committed; we can only log — cannot send a JSON error.
		slog.Error("pdf output", "err", err)
	}
}

// ----------------------------------------------------------------------------
// Handler: CoverLetterPDF
// POST /job-tracker/ai/cover-letter/pdf
// ----------------------------------------------------------------------------

type coverLetterPDFInput struct {
	Text    string `json:"text"`
	Company string `json:"company"`
	Role    string `json:"role"`
}

// CoverLetterPDF streams a PDF of the supplied cover letter text.
// No credits are debited — credits were consumed at text-generation time.
func (h *Handler) CoverLetterPDF(w http.ResponseWriter, r *http.Request) {
	var in coverLetterPDFInput
	if !readJSON(w, r, &in) {
		return
	}
	if strings.TrimSpace(in.Text) == "" {
		httpx.WriteError(w, http.StatusBadRequest, "bad_input", "text is required")
		return
	}

	pdf, err := buildCoverLetterPDF(in.Text, in.Company, in.Role)
	if err != nil {
		h.logger.Error("build cover letter pdf", "err", err)
		httpx.WriteError(w, http.StatusInternalServerError, "internal_error", "could not generate PDF")
		return
	}

	filename := sanitizeFilename(fmt.Sprintf("%s-%s-cover-letter.pdf", in.Company, in.Role))
	streamPDF(w, pdf, filename)
}

// ----------------------------------------------------------------------------
// Handler: ResumeTweakPDF
// GET /job-tracker/ai/resume/tweaks/{id}/pdf
// ----------------------------------------------------------------------------

// ResumeTweakPDF streams a PDF for an existing resume tweak row.
// Uses UserEdits when non-empty, otherwise TweakedText.
// No credits debited — PDF is free export of already-generated content.
func (h *Handler) ResumeTweakPDF(w http.ResponseWriter, r *http.Request) {
	uid := auth.MustUserID(r.Context())
	tweakID, ok := pathUUID(w, r, "id")
	if !ok {
		return
	}

	tweak, err := h.store.GetResumeTweak(r.Context(), uid, tweakID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			httpx.WriteError(w, http.StatusNotFound, "not_found", "resume tweak not found")
			return
		}
		writeDBError(w, err)
		return
	}

	bodyText := tweak.UserEdits
	if bodyText == "" {
		bodyText = tweak.TweakedText
	}

	title := tweak.Title
	if title == "" {
		title = "Untitled"
	}

	pdf, err := buildTweakPDF(title, bodyText)
	if err != nil {
		h.logger.Error("build tweak pdf", "err", err)
		httpx.WriteError(w, http.StatusInternalServerError, "internal_error", "could not generate PDF")
		return
	}

	filename := sanitizeFilename(fmt.Sprintf("resume-tweak-%s.pdf", tweakID.String()[:8]))
	streamPDF(w, pdf, filename)
}

// ----------------------------------------------------------------------------
// Handler: LatestResumeReportPDF
// GET /job-tracker/ai/resume/report/latest/pdf
// ----------------------------------------------------------------------------

// LatestResumeReportPDF streams a PDF for the user's most recent resume report.
// No credits debited — report content was already paid for at generation time.
func (h *Handler) LatestResumeReportPDF(w http.ResponseWriter, r *http.Request) {
	uid := auth.MustUserID(r.Context())

	rep, err := h.store.LatestReport(r.Context(), uid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			httpx.WriteError(w, http.StatusNotFound, "not_found", "no report found")
			return
		}
		writeDBError(w, err)
		return
	}

	plainText := stripMarkdown(rep.ReportMD)
	date := time.Now().Format("2 January 2006")
	// Use the report's actual creation date when available.
	if rep.CreatedAt != "" {
		if t, parseErr := time.Parse(`2006-01-02T15:04:05Z`, rep.CreatedAt); parseErr == nil {
			date = t.Format("2 January 2006")
		}
	}

	pdf, err := buildReportPDF(plainText, rep.Score, date)
	if err != nil {
		h.logger.Error("build report pdf", "err", err)
		httpx.WriteError(w, http.StatusInternalServerError, "internal_error", "could not generate PDF")
		return
	}

	dateStr := time.Now().Format("2006-01-02")
	if rep.CreatedAt != "" {
		if t, parseErr := time.Parse(`2006-01-02T15:04:05Z`, rep.CreatedAt); parseErr == nil {
			dateStr = t.Format("2006-01-02")
		}
	}
	filename := sanitizeFilename(fmt.Sprintf("resume-report-%s.pdf", dateStr))
	streamPDF(w, pdf, filename)
}

// ----------------------------------------------------------------------------
// Handler: ScoreReportPDF
// GET /job-tracker/ai/resume/reports/{id}/pdf
//
// PDF download for structured Resume Score reports (format = "json").
// Renders the LaTeX template at templates/ai_report/score_report.tex.tmpl
// and compiles via the sypher-tex sidecar. No credits debited — the
// AI generation was already paid for at /ai/resume/report time.
// Legacy markdown reports (format = "md") still route through the
// /report/latest/pdf path; here we return 400 if asked for one by id.
// ----------------------------------------------------------------------------
func (h *Handler) ScoreReportPDF(w http.ResponseWriter, r *http.Request) {
	uid := auth.MustUserID(r.Context())
	idStr := r.PathValue("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		httpx.WriteError(w, http.StatusBadRequest, "bad_input", "invalid report id")
		return
	}

	rep, err := h.store.GetReport(r.Context(), uid, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			httpx.WriteError(w, http.StatusNotFound, "not_found", "report not found")
			return
		}
		writeDBError(w, err)
		return
	}

	if rep.Format != "json" || len(rep.ReportJSON) == 0 {
		// Legacy Markdown reports go through the existing /latest/pdf
		// path which renders with fpdf. Refuse here so the FE doesn't
		// silently get an empty/garbled PDF.
		httpx.WriteError(w, http.StatusBadRequest, "legacy_format",
			"this report is in legacy markdown format; use /report/latest/pdf instead")
		return
	}

	var score ai.ScoreReport
	if err := json.Unmarshal(rep.ReportJSON, &score); err != nil {
		h.logger.Error("decode score report", "err", err, "report_id", id)
		httpx.WriteError(w, http.StatusInternalServerError, "decode_failed", err.Error())
		return
	}

	pdfBytes, err := RenderScoreReportPDF(r.Context(), h.latexServiceURL, &score)
	if err != nil {
		if errors.Is(err, errLatexServiceUnavailable) {
			httpx.WriteError(w, http.StatusServiceUnavailable, "latex_service_unavailable",
				"PDF compilation service is offline or not configured")
			return
		}
		h.logger.Error("compile score report pdf", "err", err, "report_id", id)
		httpx.WriteError(w, http.StatusBadGateway, "compile_failed", err.Error())
		return
	}

	dateStr := time.Now().Format("2006-01-02")
	if rep.CreatedAt != "" {
		if t, parseErr := time.Parse(`2006-01-02T15:04:05Z`, rep.CreatedAt); parseErr == nil {
			dateStr = t.Format("2006-01-02")
		}
	}
	filename := sanitizeFilename(fmt.Sprintf("resume-score-%s.pdf", dateStr))
	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	if _, err := w.Write(pdfBytes); err != nil {
		slog.Error("write score report pdf", "err", err)
	}
}
